dbt_monzo_analytics:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: project-424d7fe3-5b4f-48a0-a49
      dataset: monzo_data
      threads: 4
      keyfile: ./creds/project-424d7fe3-5b4f-48a0-a49-b28d32165ebb.json
      location: EU
  target: dev